version: "3.8"

services:
  mongo:
    image: prismagraphql/mongo-single-replica:5.0.3
    container_name: mongo
    restart: always
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=monty
      - MONGO_INITDB_ROOT_PASSWORD=pass

  # app:
  #   build: .
  #   ports:
  #     - "8000:3000"
  #   environment:
  #     - SESSION_SECRET=secret
  #     - ENVIRONMENT=production
