version: "3.8"

volumes:
  db_data:
    driver: local

services:
  mysql:
    image: mysql:latest
    container_name: db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: mdao
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"
