version: "3.8"

volumes:
  pg_data:
    driver: local

services:
  postgres:
    image: postgres:latest
    container_name: db
    restart: always
    environment:
      POSTGRES_PASSWORD: pass
      POSTGRES_USER: user
      POSTGRES_DB: mdao
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      - "5435:5432"
