app = "mdao-indexer"

[experimental]
cmd = ["yarn", "start:indexer"]

[deploy]
  release_command = "yarn reindex"

[build]
  builder = "paketobuildpacks/builder:base"
  buildpacks = ["gcr.io/paketo-buildpacks/nodejs"]