name: TODO Item
description: Log a TODO Item
title: ""
labels: ["todo"]
assignees:
  - gnomadic
body:
  - type: markdown
    attributes:
      value: |
        Got a quick item to track for development?  stash it here!
  - type: textarea
    id: description
    attributes:
      label: Todo description
      description: What's gotta get done
      placeholder: gotta do this!
      value: "Issue Description"
    validations:
      required: true
