name: Deploy Preview
on:
  pull_request:
    types: [opened, reopened, synchronize, closed]

env:
  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}

jobs:
  deploy:
    runs-on: ubuntu-latest

    # Only run one deployment at a time per PR.
    concurrency:
      group: pr-${{ github.event.number }}

    # Create a GitHub deployment environment per staging app so it shows up
    # in the pull request UI.
    environment:
      name: pr-${{ github.event.number }}
      url: ${{ steps.deploy.outputs.url }}

    steps:
      - uses: actions/checkout@v2
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl apps destroy --yes pr-${{ github.event.number }} --yes
      - run: flyctl apps create --name pr-${{ github.event.number }} --org metricsdao-614 --region iad
      - run: flyctl postgres attach mdao-pg-stg --app pr-${{ github.event.number }}
      - run: flyctl deploy --remote-only --app pr-${{ github.event.number }}
